name: ci

on:
  push:
    branches:
      - 'feature/project-setup'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout project sources
        uses: actions/checkout@v4
      -
        name: Build and push Docker image
        run: ./gradlew jib
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}